/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantsRouteImport } from './routes/tenants'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as HrRouteImport } from './routes/hr'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AiBrainRouteImport } from './routes/ai-brain'
import { Route as IndexRouteImport } from './routes/index'

const TenantsRoute = TenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const HrRoute = HrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AiBrainRoute = AiBrainRouteImport.update({
  id: '/ai-brain',
  path: '/ai-brain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-brain': typeof AiBrainRoute
  '/analytics': typeof AnalyticsRoute
  '/buyers': typeof BuyersRoute
  '/conversations': typeof ConversationsRoute
  '/finance': typeof FinanceRoute
  '/hr': typeof HrRoute
  '/leads': typeof LeadsRoute
  '/pipeline': typeof PipelineRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-brain': typeof AiBrainRoute
  '/analytics': typeof AnalyticsRoute
  '/buyers': typeof BuyersRoute
  '/conversations': typeof ConversationsRoute
  '/finance': typeof FinanceRoute
  '/hr': typeof HrRoute
  '/leads': typeof LeadsRoute
  '/pipeline': typeof PipelineRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-brain': typeof AiBrainRoute
  '/analytics': typeof AnalyticsRoute
  '/buyers': typeof BuyersRoute
  '/conversations': typeof ConversationsRoute
  '/finance': typeof FinanceRoute
  '/hr': typeof HrRoute
  '/leads': typeof LeadsRoute
  '/pipeline': typeof PipelineRoute
  '/projects': typeof ProjectsRoute
  '/properties': typeof PropertiesRoute
  '/settings': typeof SettingsRoute
  '/tenants': typeof TenantsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-brain'
    | '/analytics'
    | '/buyers'
    | '/conversations'
    | '/finance'
    | '/hr'
    | '/leads'
    | '/pipeline'
    | '/projects'
    | '/properties'
    | '/settings'
    | '/tenants'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-brain'
    | '/analytics'
    | '/buyers'
    | '/conversations'
    | '/finance'
    | '/hr'
    | '/leads'
    | '/pipeline'
    | '/projects'
    | '/properties'
    | '/settings'
    | '/tenants'
  id:
    | '__root__'
    | '/'
    | '/ai-brain'
    | '/analytics'
    | '/buyers'
    | '/conversations'
    | '/finance'
    | '/hr'
    | '/leads'
    | '/pipeline'
    | '/projects'
    | '/properties'
    | '/settings'
    | '/tenants'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiBrainRoute: typeof AiBrainRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BuyersRoute: typeof BuyersRoute
  ConversationsRoute: typeof ConversationsRoute
  FinanceRoute: typeof FinanceRoute
  HrRoute: typeof HrRoute
  LeadsRoute: typeof LeadsRoute
  PipelineRoute: typeof PipelineRoute
  ProjectsRoute: typeof ProjectsRoute
  PropertiesRoute: typeof PropertiesRoute
  SettingsRoute: typeof SettingsRoute
  TenantsRoute: typeof TenantsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenants': {
      id: '/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof TenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr': {
      id: '/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof HrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-brain': {
      id: '/ai-brain'
      path: '/ai-brain'
      fullPath: '/ai-brain'
      preLoaderRoute: typeof AiBrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiBrainRoute: AiBrainRoute,
  AnalyticsRoute: AnalyticsRoute,
  BuyersRoute: BuyersRoute,
  ConversationsRoute: ConversationsRoute,
  FinanceRoute: FinanceRoute,
  HrRoute: HrRoute,
  LeadsRoute: LeadsRoute,
  PipelineRoute: PipelineRoute,
  ProjectsRoute: ProjectsRoute,
  PropertiesRoute: PropertiesRoute,
  SettingsRoute: SettingsRoute,
  TenantsRoute: TenantsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
